# Generated by Django 3.1.3 on 2020-11-24 16:52

from django.db import migrations, models


def add_students(apps, schema_editor):
    Student = apps.get_model("dashboard", "Student")
    student = Student(1001, 'Rick', 'Davis', 'I.T.', 'Junior', 3.6)
    student.save()
    student = Student(1002, 'Miles', 'Greer', 'Physics', 'Senior', 3.8)
    student.save()
    student = Student(1003, 'David', 'Leap', 'Chemistry', 'Sophomore', 3.7)
    student.save()
    student = Student(1004, 'Rick', 'Barry', 'I.T.', 'Senior', 3.9)
    student.save()
    student = Student(1005, 'Gwen', 'Trask', 'Physics', 'Senior', 3)
    student.save()
    student = Student(1006, 'Lilly', 'Steele', 'Marketing', 'Sophomore', 3.15)
    student.save()
    student = Student(1007, 'Damon', 'Woody', 'Stats', 'Junior', 3.3)
    student.save()
    student = Student(1008, 'Tyus', 'Sneed', 'I.T.', 'Junior', 3.76)
    student.save()
    student = Student(1009, 'Drew', 'Little', 'Stats', 'Senior', 3.8)
    student.save()
    student = Student(1010, 'Maya', 'Miller', 'I.T.', 'Junior', 3.9)
    student.save()
    student = Student(1011, 'Trent', 'Davis', 'I.T.', 'Junior', 3.6)
    student.save()
    student = Student(1012, 'Rob', 'Hale', 'Physics', 'Senior', 3.8)
    student.save()
    student = Student(1013, 'David', 'Sync', 'Chemistry', 'Sophomore', 3.2)
    student.save()
    student = Student(1014, 'Eric', 'Leary', 'Stats', 'Senior', 4)
    student.save()
    student = Student(1015, 'Anya', 'Reid', 'Stats', 'Sophomore', 3.21)
    student.save()
    student = Student(1016, 'Derrick', 'Lewis', 'I.T.', 'Junior', 3.6)
    student.save()
    student = Student(1017, 'Peter', 'Cyriac', 'Physics', 'Senior', 3.8)
    student.save()
    student = Student(1018, 'Alton', 'Chase', 'Chemistry', 'Sophomore', 3.5)
    student.save()
    student = Student(1019, 'Monica', 'Monroe', 'Physics', 'Sophomore', 3.3)
    student.save()
    student = Student(1020, 'Abby', 'Mathew', 'I.T.', 'Junior', 4)
    student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_students),
    ]
